### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by OneMiay** [NateRickard/Xamarin.Cognitive.BingSpeech#6] opened 2018-06-13 11:50 UTC
Authentification is successful and a token comes in, but when sending a wav file, the answer is Error 403 Forbidden.

Real device with Android 7.1

**Comment by OneMiay** [comment] 2018-06-15 00:14
![image](https://user-images.githubusercontent.com/1555673/41444190-2c477ab8-704a-11e8-8197-7c9fd4ae68cf.png)

How to fix?

**Comment by NateRickard** [comment] 2018-06-28 20:49
The 403 would be coming back from the service, so that's likely unrelated to the error in the block you identified above.

What's the exception?  Is the audio length maybe exceeding the bounds of an Int32?  Can you provide a reproduction project?

You may want to try v2.0.0 as there were a few things fixed, but nothing specific to the issue you're experiencing.

**Comment by NateRickard** [comment] 2018-07-23 20:53
Closing since it's been almost a month with no further details.  Feel free to reopen if you think there's a legit issue here and you can let me know how to reproduce it.

**Closed as completed by NateRickard** 2018-07-23 20:53 UTC
